brann_analytics:
  outputs:
    dev:
      type: duckdb
      path: '../data/brann.duckdb'
      threads: 4
      timeout_seconds: 300
    prod:
      type: duckdb
      path: '../data/brann.duckdb'
      threads: 4
      timeout_seconds: 300
  target: dev
