[project]
name = "brann-tickets-scraping"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    "beautifulsoup4",
    "dbt-duckdb>=1.11.0",
    "duckdb>=1.5.5",
    "langchain>=1.0.0",
    "langchain-openai>=1.0.0",
    "langgraph>=1.0.0",
    "openai>=2.0.0",
    "polars",
    "polars_ds",
    "pyarrow>=25.0.1",
    "python-dotenv>=1.0.0",
    "requests",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
